### ISSUE TITLE
Error when trying to convert some HKX files

### ISSUE THREAD

**Issue by Sanadsk** [Dexesttp/hkxpack#19]
Hello! There are some files which have this header: 

> hkClass..§ï°.hkClassMember.د.6ٹ.hkClassEnum.lٹoخ.hkClassEnumItem..ءr'.hkRootLevelContainer.Lں…&.hkaAnimationContainer.غخء‏.hkaSkeleton.ٍَï¥.hkaInterleavedUncompressedAnimation.P‘¯..hkaAnimationBinding.(ف“ہ.hkxScene.°Iê..hkxNode.i´3+.hkxSparselyAnimatedString..{ٍْ.hkxSparselyAnimatedInt.ن–d,.hkxSparselyAnimatedBool.TاV’.hkxAnimatedFloat.T.شa.hkxCamera.RCشZ.hkxSpline.s:ل..hkMemoryResourceContainer

When I try to convert them, it tells me:
`java.lang.NullPointerException
        at com.dexesttp.hkxpack.descriptor.reader.ClassXMLReader.get(ClassXMLReader.java:53)
        at com.dexesttp.hkxpack.descriptor.HKXDescriptorFactory.get(HKXDescriptorFactory.java:38)
        at com.dexesttp.hkxpack.hkxreader.HKXReader.read(HKXReader.java:91)
        at com.dexesttp.hkxpack.cli.commands.Command_unpack.execution_core(Command_unpack.java:29)
        at com.dexesttp.hkxpack.cli.commands.Command_IO.execute_single(Command_IO.java:75)
        at com.dexesttp.hkxpack.cli.commands.Command_IO.execute(Command_IO.java:59)
        at com.dexesttp.hkxpack.cli.ConsoleView.main(ConsoleView.java:17)`

I hope you know what the issue might be. I can send the files if needed.
Thanks so much for this amazing tool!

**Comment by Dexesttp** [comment]
Hello, thanks for the report ! This seems due to the file you are trying to read containing data from an earlier or later version that the one you are working with.

The "proper" fix is to make this a clearer exception, indicating the class name and such, so the change for this has been made in f7c7bd05db90b435ee51efcc503484cb94177bb3. However, note that this won't solve the issue itself.
